const cars = [
    {
        name: "AUDI",
        make: "AUDI",
        model: "Class S",
        year: 2014,
        mileage: "104,556",
        version: "1.6 hdi",
        fuel: "Diesel",
        engine: "1900",
        horsepower: 200,
    },
    {
        name: "ACURA",
        make: "Acura",
        model: "Integra Type S",
        year: 2024,
        mileage: "0",
        version: "2.0 Turbo",
        fuel: "Petrol",
        engine: "1996",
        horsepower: 320,
    },